name: Database Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  database-integrity:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in $(seq 1 10); do
            pnpm db:test-connection && break
            sleep 5
          done

      - name: Run database migrations
        run: pnpm db:migrate

      - name: Run API tests (if any)
        run: pnpm test:api
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/testdb
